service: serverless-example

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  
useDotenv: true

custom:
  dotenv:
    path: ./.env

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}



functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
